name: Build and Run Image

on:
  workflow_dispatch:
  push:
    branches: main

env:
  DOCKER_IMAGE_NAME: "node-app-project"

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: |
          IMAGE_NAME="$DOCKER_IMAGE_NAME:${{ github.sha }}"
          echo "IMAGE_NAME=$IMAGE_NAME"
          echo "IMAGE_NAME=$IMAGE_NAME" >> $GITHUB_ENV
          docker build -t ${{ env.IMAGE_NAME }} .

      - name: Start minikube
        uses: medyagh/setup-minikube@latest

      - name: Load image to minikube
        run: |
          minikube image load ${{ env.IMAGE_NAME }}
          echo "Loaded image"
          minikube image ls

      - name: Run using kubectl command
        run: |
          sed -i "s/node-app:1.0/${{ env.IMAGE_NAME }}/" deployment.yaml
          kubectl apply -f deployment.yaml
          sleep 30
          kubectl get all
          POD_NAME=$(kubectl get pod --selector app=node-app -o=jsonpath='{.items[0].metadata.name}{"\n"}')
          kubectl describe pod $POD_NAME
      
      - name: Print pod and container log
        run: |
          echo "-------------------------------------------------------------------------"
          echo "POD LOG:"          
          kubectl logs $POD_NAME
          echo "-------------------------------------------------------------------------"
          echo "CONTAINER LOG"
          kubectl exec -it $(kubectl get pod --selector app=node-app -o=jsonpath='{.items[0].metadata.name}{"\n"}') -- curl http://localhost:3000
          echo "-------------------------------------------------------------------------"
